project_id = "sjjwswpxrjublpmrnoca"

[functions.generate-product-image]
verify_jwt = false

[functions.upload-local-images]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.login-user]
verify_jwt = false

[functions.approve-user]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.complete-order]
verify_jwt = false

[functions.deactivate-user]
verify_jwt = false

[functions.manage-admin]
verify_jwt = false

[functions.manage-site-settings]
verify_jwt = false

[functions.manage-announcements]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.store-status-webhook]
verify_jwt = false

[functions.process-job-application]
verify_jwt = false

[functions.upload-delivery-proof]
verify_jwt = false

[functions.auto-store-status]
verify_jwt = false

[functions.discord-bot]
verify_jwt = false

[functions.discord-bot-setup]
verify_jwt = false
